### ISSUE TITLE
Add indices on geoid columns

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-factfinder-api#254]
In an effort to tackle some low-hanging fruit that should improve the performance of PFF database queries, we want to add [postgres indices](https://www.postgresql.org/docs/current/indexes.html) to the `geoid` columns found in several of our tables.

The bulk of the actual data for PFF exists in 4 tables - the "current" and "previous" year tables for ACS and Decennial data. The database has a schema (folder) for acs and decennial and within each of those are tables for previous and current. Our queries [look up data](https://github.com/NYCPlanning/labs-factfinder-api/blob/develop/query-helpers/decennial.js#L30) from those tables with a `WHERE` clause on the `geoid` column.

## Context on how existing migration scripts work

1. Running the `migrate` npm script in `package.json` runs the file at `/bin/migrate`.
2. This file kicks off a series of bash and sql scripts in the `/migrations` folder that create the tables for the database and load the data.
3. These scripts rely heavily on constants pulled from `/special-calculations/data/constants.js`
4. Among the tables created and populated are four tables that hold the actual ACS and decennial census data. These tables are placed into schemas: `acs` and `deceninal`.
5. Two tables are created are created in each of these two schemas, named for the year that the data within the table corresponds too. At time of writing, the `acs` schema should have tables named `2010` and `2021`, decennial should have `2010` and `2020`. These values come from the values for ACS_EARLIEST_TABLE_NAME, ACS_LATEST_TABLE_NAME, DECENNIAL_EARLIEST_TABLE_NAME, and DECENNIAL_LATEST_TABLE_NAME in `constants.js`
6. These values are passed through the bash and sql scripts to be used to name the schemas and tables. They will be assigned to the `"TABLE_NAME" variable referenced in `decennial.sql` and `acs.sql`.

## Acceptance Criteria
1. Update the sql in `migrations/decennial.sql` and `migrations/acs.sql` to add a [postgres index](https://www.postgresql.org/docs/current/indexes.html) on the `geoid` columns of those tables. You may also add the indices via a new separate sql script if that is easier, but in that case the related bash script workflow should be updated to run your new script. This should create 4 indices - one on the `geoid` column of each of the four tables mentioned above
2. The script should ideally name the index dynamically to denote the schema, table, and column that the index is indexing. This would be similar to how the `acs.sql` and `decennial.sql` scripts already make use of their `TABLE_NAME` variable to dynamically name the table with that variable. The naming convention we want for the indices is as follows: ``<survey>_<year>_<column>_idx`. At time of writing, this would mean the actual index names should come out to:
   * `acs_2010_geoid_idx`
   * `acs_2021_geoid_idx`
   * `decennial_2010_geoid_idx`
   * `decennial_2020_geoid_idx`
3. We will be bundling the deployment to production for this change with the updating data updates. Therefore, put up a PR once you are able to run the migration scripts locally and have confirmed that the tables are successfully created and populated, with the new indices created as well.

**Comment by TangoYankee** [comment]
@Tyler if memory serves, there was previous work in creating these indices. Is there an existing branch with that work which could be linked for reference?

Also, the paragraph style makes it difficult for me to parse all the requirements. Could we reformat this into a checkbox list of acceptance criteria?

**Comment by TylerMatteo** [comment]
@TangoYankee @bmarchena I don't have any code from my initial exploration of this but I didn't get beyond adding the indices manually with some `CREATE INDEX` statements, so there wasn't much there to go off of. I updated the description with clearer AC but reach out if there is still any confusion.
