### ISSUE TITLE
Issue/16067 PFF Updates: Top & Bottom Thresholds

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-factfinder-api#256]
### Ticket 
[Issue 16067](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16067) 
[Workflow branch strategy](https://github.com/NYCPlanning/labs-factfinder/issues/1134)

#### Economic:  (`PREV_YEAR` changes)
 - Top-and bottom-coding changes: 
   - MdHHInc: 
     - [x] Top: median calculation: 200,000, inflated/shown as: 270,000+ 
     - [x] Bottom: median calculation: 9,999, inflated/shown as: 13,500- 
   - MdFamInc: 
     - [x] Top: median calculation: 200,000, inflated/shown as: 270,000+ 
     - [x] Bottom: median calculation: 9,999, inflated/shown as: 13,500- 
   - MdNFInc: 
     - [x] Top: median calculation: 200,000, inflated/shown as: 270,000+ 
     - [x] Bottom: median calculation: 9,999, inflated/shown as: 13,500- 
   - MdEWrk: 
     - [x] Top: median calculation: 100,000, inflated/shown as: 135,000+ 
     - [x] Bottom: median calculation: 2,499, inflated/shown as: 3,400- 
   - MdEMFTWrk: 
     - [x] Top: median calculation: 100,000, inflated/shown as: 135,000+ 
     - [x] Bottom: median calculation: 2,499, inflated/shown as: 3,400- 
   - MdEFFTWrk: 
     - [x] Top: median calculation: 100,000, inflated/shown as: 135,000+ 
     - [x] Bottom: median calculation: 2,499, inflated/shown as: 3,400-
 #### Housing: 
 - Top- and bottom-coding changes: 
   - MdVl: 
     - [x] Top: median calculation: 1,000,000, inflated/shown as: 1,350,000+ 
     - [x] Bottom: no bottom coding 
   - MdGR: 
     - [x] Top: median calculation: 2,000, inflated/shown as: 2,700+ 
     - [x] Bottom: no bottom coding 

###### note: ff api `special-calculations/data/top-bottom-codings.js` here:  [PR Reference](https://github.com/NYCPlanning/labs-factfinder-api/pull/195/files)

**Comment by TylerMatteo** [comment]
@horatiorosa  todo: link to PR from previous top/bottom codings updats

**Comment by pratishta** [comment]
Directly pushed to `issue/16067` with commit https://github.com/NYCPlanning/labs-factfinder-api/commit/8279b31
