### ISSUE TITLE
Issue/16067 PFF Updates: Update Constants

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-factfinder-api#268]
### Ticket 
[Issue 16067](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16067)
[Workflow branch strategy](https://github.com/NYCPlanning/labs-factfinder/issues/1134)
  
 - [x] Update `INFLATION_FACTOR` to 1.3493
 - [x] Update `CUR_YEAR` to 2018-2022 (Any instance of 2017-2021 will need to be updated to 2018-2022 )

###### note: 👀  `special-calculations/data/constants.js` here: [PR Reference](https://github.com/NYCPlanning/labs-factfinder-api/pull/196/files)

**Comment by pratishta** [comment]
I couldn't find any instance of having to update `CUR_YEAR` to 2018-2028 in the ADO issue, so I'm going to assume it's actually 2018-2022, let me know if I'm misinterpreting.

**Comment by horatiorosa** [comment]
> I couldn't find any instance of having to update `CUR_YEAR` to 2018-2028 in the ADO issue, so I'm going to assume it's actually 2018-2022, let me know if I'm misinterpreting.

A terrible copy/paste fail. I updated the issue description to correct and clarify. My bad.

**Comment by pratishta** [comment]
Closing PR and directly pushing to `issue/16067` with commit 329a33380dcdf70c1a69380bee0015e9d74cf18d
