### ISSUE TITLE
Issue/16067 PFF Updates: Clean up unnecessary "Drop Table" command

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-factfinder-api#283]
### Ticket 
[Issue 16067](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16067)

#### Related to:
Issue #282 

### Description
Clean up the the following line to the `acs.sql` file after the PFF data updated has been QA-ed and deployed.
`DROP TABLE IF EXISTS acs.:"2021";`

**Comment by TylerMatteo** [comment]
Closing because this (arguably) isn't necessary - as long as the drop command added  in #282 has `IF EXISTS`, we can safely leave it in.
