### ISSUE TITLE
Change percent MOE should only be null if previous estimate is 0

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder-api#29]
Right now: if 2012-2016 estimate is 0, the change percent MOE is null
Change percent MOE should have a value unless previous estimate is 0
This should allow an MOE to be calculated for -100 percent change

![image](https://user-images.githubusercontent.com/32674674/36354017-17d9cafe-149c-11e8-8720-1c8f803febf4.png)

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-05 at 10.17.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2a56415c4cbc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14f53a713306ae470326e0a.png)

^ Percent Change Estimate MOE should be calculated (not null)

**Comment by allthesignals** [comment]
<img width="1761" alt="screen shot 2018-03-07 at 3 17 05 pm" src="https://user-images.githubusercontent.com/5004319/37115918-a1d437d6-221a-11e8-96fb-0729f54c7fd5.png">
Link here https://nyc-factfinder.planninglabs.nyc/profile/851/demographic?charts=false&mode=change&reliability=true

**Comment by allthesignals** [comment]
@EricaMaurer I need an example of where this is happening so I can debug it. I can't tell from the screenshots. THanks.

**Comment by EricaMaurer** [comment]
@allthesignals https://nyc-factfinder.planninglabs.nyc/profile/851/economic?charts=false&mode=change&reliability=true  Commute to Work--  Car, truck, or van -- carpooled

![image](https://user-images.githubusercontent.com/32674674/37116645-e8a7d968-221c-11e8-88fe-c80176334f9c.png)

This is happening when there is a value in 2006-2010 and a 0 for 2012-2016, the percent change is -100%, there should be an MOE.. right now the percent change MOE is blank.

The example you posted above: https://nyc-factfinder.planninglabs.nyc/profile/851/demographic?charts=false&mode=change&reliability=true for Hispanic- Honduran and Nicaraguan WAS correctly displaying blank percent change estimate and MOE since 2006-2010 is 0 or both the 2006-2010 and 2012-2016 are 0. Now the app is showing a 0 percent change.

**Comment by allthesignals** [comment]
I get the first thing, but why does it matter for the second? Both estimates are a 0, unreliable, and the change between the two years is coded unreliable, and if they were reliable, the change would be 0 percent.

**Comment by allthesignals** [comment]
If someone mistakenly uses "0 percent change" statistic (that's already coded UNRELIABLE), what else is there to do?

**Comment by EricaMaurer** [comment]
The second thing is ok to leave as it is

**Comment by allthesignals** [comment]
Here's the math I have for that:

```sql
            ABS(sum / NULLIF(previous_sum,0))
            * SQRT(
              (POWER(coalesce(m, 0) / 1.645, 2) / NULLIF(POWER(sum, 2),0))
             + (POWER(previous_m / 1.645, 2) / NULLIF(POWER(previous_sum, 2),0))
            ) * 1.645
```

In the case of that variable, `sum` is `0` and `previous_sum` is `39`, so it would always be 0. Should the margin of error for that calculation be zero?

**Comment by allthesignals** [comment]
I think it's coming out as null because of the division by zero protections - in the SQRT, it says square the sum (which is 0), then make it null if it's 0. 0^2 is 0 so it makes it null in this case. Then, 0 * null = null. I could coalesce the SQRT to be 0 if it's null, but in terms of the big picture, I don't see what the big deal is. This seems like a very low severity issue, unless the math is wrong and it's not calculating the MOE correctly.

**Comment by EricaMaurer** [comment]
So now we don't have a division by zero protection for percents... so we would need to add it back for percents (but we pulled back on before)... so I guess we also remove the protection from the MOE formula. Or would just remove the nullif from the sum part of the formula because the original rule was that it should only be null if the previous estimate was 0.

**Comment by allthesignals** [comment]
> So now we don't have a division by zero protection for percents...
I don't follow what you mean

> so I guess we also remove the protection from the MOE formula
We can't do that because the query will fail. Computers throw errors when you try to divide by zero. If the input value is 0, it will need to be coerced into a null. Postgres considers null as simply "unknown" and therefore the full calculation can't be made because certain inputs are unknown to it.

So what should the margin of error be for the percentage change of `Car, truck, or van -- carpooled'` ? 
![image](https://user-images.githubusercontent.com/5004319/37174206-de2ef792-22e3-11e8-9ed5-aa1e609be580.png)

**Comment by EricaMaurer** [comment]
Should be 0

**Comment by allthesignals** [comment]
Okay. I can fix that by coercing certain values.

**Comment by allthesignals** [comment]
Alright, here's my logic:

```sql
CASE
  WHEN is_most_recent AND previous_sum != 0 THEN
    coalesce(
      ABS(sum / NULLIF(previous_sum,0))
      * SQRT(
        (POWER(coalesce(m, 0) / 1.645, 2) / NULLIF(POWER(sum, 2), 0))
        + (POWER(previous_m / 1.645, 2) / NULLIF(POWER(previous_sum, 2), 0))
      ) * 1.645,
      0
    )
END as change_percent_m
```

When there is a previous_sum, calculate percent_m and coalesce it into `0` if it's null.

**Comment by EricaMaurer** [comment]
![image](https://user-images.githubusercontent.com/32674674/37776877-a354861c-2dbc-11e8-8e97-4b3439bf5bd8.png)

<-- For Data Issues -->
Link to profile where behavior is occurring: Example: https://nyc-factfinder.planninglabs.nyc/profile/1025/social?mode=change&reliability=true
Is this a single geography selection or a multiple (aggregation) geography selection?: single
Which profile is this in (Census, Demographic, Social, Economic, Housing)?: All ACS profiles
Name of variable(s) where behavior is occurring (or is it all variables?): from example: Place of Birth- Jordan
Is this in the change over time view or the current year view?: change over time
If change over time view, is it in 2000, 2010, 2006-2010, or 2012-2016 columns?:
Which calculation is it (estimate, margin of error, cv, percent, percent margin of error, difference, change, etc?): percent change moe
What is the value now and what should it be instead? What is the significance coding now and what should it be instead?: MOE is currently blank, should be 0. MOE should be calculated because there is a value in the previous period.

**Comment by hannahkates** [comment]
Is this still an issue?

**Comment by allthesignals** [comment]
@EricaMaurer still an issue?

**Comment by EricaMaurer** [comment]
i'll look into it

**Comment by EricaMaurer** [comment]
fixed
