### ISSUE TITLE
Top-coding logic (graying, +, MOE & CV blank) not being applied to variables

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder-api#32]
Thought this was done with PR #503 and #14, but top-coding logic does not seem to be applied to variables.

Median family income and median earnings for male full-time, year-round workers (dollars) are top-coded values-- should be gray and MOE and CV should be blank

https://nyc-factfinder.planninglabs.nyc/profile/726/economic?reliability=true

 
![image](https://user-images.githubusercontent.com/32674674/36357565-d91ef730-14cd-11e8-9f3b-12bd2ca87a0f.png)

**Comment by allthesignals** [comment]
It's not getting the topCoding information - it's a multi-geog aggregation. 

<img width="507" alt="screen shot 2018-02-25 at 12 18 53 pm" src="https://user-images.githubusercontent.com/5004319/36644296-143b4c26-1a26-11e8-8299-5cca1849a0da.png">

**Comment by EricaMaurer** [comment]
multi-geogs are the ones that get all the top-coding logic
and we decided single geogs don't get "+" because it couldn't get added to the data that wasn't getting touched.
But all top-coded variables (single and multi) should at least appear gray

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-05 at 10.14.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2a55415d4cbc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14f53a61b3e62e0713f6e0a.png)

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-06 at 3.02.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f56b7191a37bf112294f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19141c95df44be24b53a11b3566e4772431.png)
