### ISSUE TITLE
2013-2017 ACS data updates

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-factfinder-api#44]
Need to update json configuration. Amount of related work depends on whether these are special variables.

The new data has a new schema, with both new and deleted columns.

New variables appear in special variables and do not appear in profile:

- Social:
  - HH4
  - Fam3
- Economic:
  - WrkrNotHm
  - HH5

Variables removed from database:

- Social: UWHUSmpl1 (dependent special calcs replaced by new CV calc)
- Economic: UWHUSmpl2, UWPopSmpl (dependent special calcs replaced by new CV calc)
- Housing: UWHUSmpl3 (dependent special calcs replaced by new CV calc)

**Comment by allthesignals** [comment]
All of these changes are actually changes to new formulas for calculating MOEs for means and CVs. Once we update the data, this can be closed.

**Comment by allthesignals** [comment]
These changes are being reviewed in this PR: https://github.com/NYCPlanning/labs-factfinder/pull/690

**Comment by allthesignals** [comment]
It's 2020!
