### ISSUE TITLE
Make tract styling more prominent in block view

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-factfinder-api#48]
- Make tract outline thicker
- Improve visibility of tract label at different scales

**Comment by hannahkates** [comment]
I've identified a line width that I think looks good in f5d9926ceb207eea0faa554daf81a821825253a5, but I think I need to wait to implement until #644 is merged in since that will change how the layers are styled.

**Comment by allthesignals** [comment]
#644 is merged - does https://github.com/NYCPlanning/labs-factfinder/compare/tract-styling need to be PR'd?
