### ISSUE TITLE
Rename variables to be clearer

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-factfinder-api#56]
@trbmcginnis did a lot of research and found we should rename variables for the Row model. Things like "m", margin of error, are confusing and should be improved. 

We should carve out maintenance time alongside other refactoring tasks to address this.

**Comment by trbmcginnis** [comment]
Started to make changes in branch `variable-name-changes`, leaving this for now (still needs work with failing tests, double checking variables, etc.), but we can revisit during a bigger refactor.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-factfinder #756](https://github.com/NYCPlanning/labs-factfinder/issues/756) via [**ZenHub**](https://www.zenhub.com/)
