### ISSUE TITLE
Change Significant to Reliable to reflect calculation changes

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-factfinder-api#57]

**Comment by trbmcginnis** [comment]
Updates were made to calculations in the API-->calculations were changed from originally reflecting statistical SIGNIFICANCE to reflect statistical RELIABILITY in this PR: https://github.com/NYCPlanning/labs-factfinder-api/commit/a2f5e2fdf72445eb3f8ac4cd65678002bc939804#diff-ea8ffe18650f7aa9dd4ccabade57d3d6. 

Variable names were not updated to reflect this change. For the sake of time, I added comments in both the API and the frontend to note these changes in this PR: ______. These names will be updated during a broader refactor of PFF, as for now these names are aliased for the sake of the CSV download column titles in PFF: _______.

**Comment by allthesignals** [comment]
Unsure if this is still an issue. Do you remember @trbmcginnis?

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-factfinder #755](https://github.com/NYCPlanning/labs-factfinder/issues/755) via [**ZenHub**](https://www.zenhub.com/)
