### ISSUE TITLE
Check median earnings MOE

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder-api#91]
https://factfinder-staging.planninglabs.nyc/profile/36642/demographic?reliability=true

PFF: Estimate: 67,581 MOE: 11,318
What I am getting: Estimate: 67,580 MOE: 11,405
Lower bound: 60,510 Upper bound: 74,377

**Comment by allthesignals** [comment]
@EricaMaurer 

I think this issue needs more detail. Is this something I need to look into?

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-factfinder #747](https://github.com/NYCPlanning/labs-factfinder/issues/747) via [**ZenHub**](https://www.zenhub.com/)
