### ISSUE TITLE
Residence 1 Year Ago

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder-api#93]
Percent are being calculated off of wrong base-- this might be an issue for EDM instead.
For Queens, which should be pulled directly from the database
Under Population 1 year and over that lived in a different house:
- different house in US
- same county
- different county
- abroad
![image](https://user-images.githubusercontent.com/32674674/74055075-4ee4aa80-49ad-11ea-8007-2db82d126800.png)
https://factfinder-staging.planninglabs.nyc/profile/36646/social?comparator=4&reliability=true

**Comment by allthesignals** [comment]
Are you referring to the Queens (comparison) columns or the Selection Area columns? 

This might be a metadata issue. I would check the PFF metadata.

**Comment by EricaMaurer** [comment]
Referring to the Queens (comparison) columns

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-factfinder #745](https://github.com/NYCPlanning/labs-factfinder/issues/745) via [**ZenHub**](https://www.zenhub.com/)
